name: Continus Intergaton - Build Docker image and push to Cloud

on:
  push:
    branches:
      - main
      - develop
      - releases/**
  pull_request:
    branches:
      - main
      - develop
      - releases/**

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - run: npm install -g pnpm
      - run: pnpm test
    


