name: CI - Test, Scan, Build and Publish Docker image and push to Cloud

on:
  push:
    branches:
      - main
      - develop
      - releases/**
  pull_request:
    branches:
      - main
      - develop
      - releases/**

env:
  LOG_LEVEL: 'verbose'
  SECRET: ${{ secrets.SECRET }}

jobs:
  test:
    name: Testing with Jest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - run: npm install -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm test

  code-analysis:
    name: Code analysis with SonarCloud
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  publish:
    name: Publish the Docker image
    runs-on: ubuntu-latest 
    needs: [code-analysis, scan]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: khantki/urlshortener-with-nest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}